import type { IconProp } from '@fortawesome/fontawesome-svg-core'
import {
  faBitbucket,
  faDiscord,
  faDribbble,
  faFacebookF,
  faGithub,
  faGitlab,
  faInstagram,
  faLinkedin,
  faMediumM,
  faPatreon,
  faPinterestP,
  faReddit,
  faSlack,
  faSnapchat,
  faTiktok,
  faTwitch,
  faVimeo,
  faXTwitter,
  faYoutube,
} from '@fortawesome/free-brands-svg-icons'

/**
 * Icon names for Font Awesome 6 brand icons
 */
export const SOCIAL_ICON_MAP: Record<string, string> = {
  facebook: 'faFacebookF',
  twitter: 'faXTwitter',
  x: 'faXTwitter',
  instagram: 'faInstagram',
  linkedin: 'faLinkedinIn',
  youtube: 'faYoutube',
  pinterest: 'faPinterestP',
  snapchat: 'faSnapchat',
  tiktok: 'faTiktok',
  twitch: 'faTwitch',
  vimeo: 'faVimeo',
  github: 'faGithub',
  gitlab: 'faGitlab',
  bitbucket: 'faBitbucket',
  medium: 'faMediumM',
  patreon: 'faPatreon',
  reddit: 'faReddit',
  slack: 'faSlack',
  discord: 'faDiscord',
}

export const SOCIAL_ICON_PROP_MAP: Record<string, IconProp> = {
  facebook: faFacebookF,
  dribbble: faDribbble,
  twitter: faXTwitter,
  x: faXTwitter,
  instagram: faInstagram,
  linkedin: faLinkedin,
  youtube: faYoutube,
  pinterest: faPinterestP,
  snapchat: faSnapchat,
  tiktok: faTiktok,
  twitch: faTwitch,
  vimeo: faVimeo,
  github: faGithub,
  gitlab: faGitlab,
  bitbucket: faBitbucket,
  medium: faMediumM,
  patreon: faPatreon,
  reddit: faReddit,
  slack: faSlack,
  discord: faDiscord,
}
