#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run `bunx` if bun installed, if run `npmx` instead
if command -v bun >/dev/null 2>&1; then
  echo "Using bun..."
  bunx lint-staged
else
  echo "Using npm..."
  npx lint-staged
fi
